site_name: AeroNode
nav:
  - 'index.md'
  - 'installation.md'
  - 'how-to-do-x/index.md'
repo_url: https://github.com/akxcix/aeronode-docs/
edit_uri: blob/main/docs/
theme:
  name: readthedocs
  locale: en
  features:
    - content.action.edit
